login: &common
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: cybage@123
  host: 172.28.36.51
  port: 5432
  database: rails-blog
  min_messages: warning # silence the NOTICE: messages from postgres


development:
  <<: *common

qa:
  <<: *common

stg:
  <<: *common

production:
  <<: *common

test:
  <<: *common